kind: Deployment
apiVersion: apps/v1
metadata:
  name: advcide-deployment
  namespace: advcicd
  labels:
    app: advcicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: advcicd
  template:
    metadata:
      labels:
        app: advcicd
    spec:
      containers:
        - name: advcicd-container
          image: devendracode1910/advcicd:latest
          ports:
          - containerPort: 5500

