kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: advcicd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5173"
    prometheus.io/path: "/"
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: advcicd
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
